name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: elixio_uninstaller

  build-and-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wine
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter requests

      - name: Build executable
        run: |
          wine pyinstaller --onefile --noconsole --name elixio_uninstaller.exe main.py
          ls -R dist

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/elixio_uninstaller.exe
          asset_name: elixio_uninstaller.exe
          tag: ${{ needs.release-please.outputs.tag_name }}
          overwrite: true

      - name: Upload config.json to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: config.json
          asset_name: config.json
          tag: ${{ needs.release-please.outputs.tag_name }}
          overwrite: true
