name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Check out your repository

      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

      - name: Get latest release version
        id: get_release
        run: |
          repo_owner='LupuC'
          repo_name='elixio_uninstaller'
          url="https://api.github.com/repos/${repo_owner}/${repo_name}/releases/latest"
          latest_version=$(curl -s $url | jq -r '.tag_name')
          echo ::set-output name=latest_version::${latest_version}

          

      - name: Install PyInstaller
        run: pip install pyinstaller


      - name: Check repository contents
        run: |
          ls -l ${GITHUB_WORKSPACE}

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole main.py
          echo "done, checking files.."
          ls dist
          ls -l dist  # Debug: List contents of dist directory
          
      - name: Check repository contents 2
        run: |
          ls -l ${GITHUB_WORKSPACE}

      - name: Go to dist
        run: |
          cd dist
          ls
          
      - name: Prepare release files
        run: |
          mv dist/main elixio_uninstaller.exe  # Rename main.exe as needed
          mkdir release
          mv elixio_uninstaller.exe release/
          cp config.json release/
        working-directory: ${{ github.workspace }}

      - name: Check if update is needed and update config.json
        run: |
          latest_version=${{ steps.get_release.outputs.latest_version }}
          current_version=$(cat config.json | jq -r '.version')
          if [ "$latest_version" != "$current_version" ]; then
            echo '{"name": "Elixio Uninstaller", "version": "'$latest_version'"}' > config.json
            git config --global user.email "github-actions@github.com"
            git config --global user.name "GitHub Actions"
            git add config.json
            git commit -m "Update version to $latest_version"
            git push origin main
          else
            echo "No update needed. Exiting gracefully."
          fi
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/elixio_uninstaller.exe

