name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Check out your repository

      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

      - name: Get latest release version
        id: get_release
        run: |
          repo_owner='LupuC'
          repo_name='elixio_uninstaller'
          url="https://api.github.com/repos/${repo_owner}/${repo_name}/releases/latest"
          latest_version=$(curl -s $url | jq -r '.tag_name')
          echo ::set-output name=latest_version::${latest_version}

      - name: Update config.json with latest version
        run: |
          latest_version=${{ steps.get_release.outputs.latest_version }}
          echo '{"name": "Elixio Uninstaller", "version": "'$latest_version'"}' > config.json
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add config.json
          git commit -m "Update version to $latest_version"
          git push origin main

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --noconsole main.py

      - name: Prepare release files
        run: |
          mv dist/main.exe elixio_uninstaller.exe  # Rename main.exe as needed
          mkdir release
          mv main.exe release/
          cp config.json release/
        working-directory: ${{ github.workspace }}

      - name: Package release artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: release
