name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run release-please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: elixio_uninstaller

      - name: Log release-please outputs
        run: |
          echo "Release created: ${{ steps.release.outputs.release_created }}"
          echo "Release name: ${{ steps.release.outputs.name }}"
          echo "Tag name: ${{ steps.release.outputs.tag_name }}"
          echo "Upload URL: ${{ steps.release.outputs.upload_url }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wine
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter requests
          pip list

      - name: Build executable
        run: |
          wine pyinstaller --onefile --noconsole --name elixio_uninstaller.exe main.py
          echo "Contents of current directory:"
          ls -la
          echo "Contents of dist directory:"
          ls -la dist

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/elixio_uninstaller.exe
          asset_name: elixio_uninstaller.exe
          tag: ${{ steps.release.outputs.tag_name }}
          overwrite: true

      - name: Upload config.json to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: config.json
          asset_name: config.json
          tag: ${{ steps.release.outputs.tag_name }}
          overwrite: true

      - name: Log final status
        run: |
          echo "Workflow completed. Check the logs above for details on each step."
          echo "If the release was created, the binaries should now be uploaded."
          echo "If no release was created, no uploads would have occurred."
