name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run release-please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

  build-and-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter requests

      - name: Build executable
        run: pyinstaller --onefile --noconsole --name elixio_uninstaller main.py

      - name: Update config.json
        run: |
          $version = '${{ needs.release-please.outputs.tag_name }}'
          $json = Get-Content config.json | ConvertFrom-Json
          $json.version = $version
          $json | ConvertTo-Json | Set-Content config.json

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/elixio_uninstaller.exe
          asset_name: elixio_uninstaller.exe
          tag: ${{ needs.release-please.outputs.tag_name }}
          overwrite: true

      - name: Upload config.json to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: config.json
          asset_name: config.json
          tag: ${{ needs.release-please.outputs.tag_name }}
          overwrite: true
