name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

      - name: Get latest release version
        id: get_release
        run: |
          repo_owner='LupuC'
          repo_name='elixio_uninstaller'
          url="https://api.github.com/repos/${repo_owner}/${repo_name}/releases/latest"
          latest_version=$(curl -s $url | jq -r '.tag_name')
          echo ::set-output name=latest_version::${latest_version}

      - name: Update config.json with latest version
        run: |
          latest_version=${{ steps.get_release.outputs.latest_version }}
          echo '{"name": "Elixio Uninstaller", "version": "'$latest_version'"}' > config.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add config.json
          git commit -m "Update version to $latest_version"
          git push
